version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./db:/db
    environment:
      POSTGRES_HOSTNAME: web
      POSTGRES_PASSWORD: password
  backend:
    build: ./backend
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/backend
    ports:
      - "3001:3001"
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend