version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./db:/db
    environment:
      POSTGRES_HOSTNAME: backend
      POSTGRES_PASSWORD: password
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "3001:3001"
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend